import { NextRequest, NextResponse } from 'next/server'

const OPPS = [
  // ── SOFTWARE & TECH ──────────────────────────────────────────────
  { name: 'Freelance software development', cat: 'Software & Tech', cost: 'Free', income: '$3k–$12k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['tech', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'product'], environment: ['home'], how: 'You find businesses or startups that need custom software built and charge per project. Start on Upwork or by cold outreach to local businesses. Over time raise your rates and collect referrals. The scale play is hiring developers and running an agency where you sell and manage while your team builds — turning yourself from a coder into a business owner.' },

  { name: 'SaaS product development', cat: 'Software & Tech', cost: 'Free', income: '$500–$20k+/mo', timeToFirst: '3–6 months', diff: 'Advanced', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding'], physical: false, goalFit: ['build_business'], interests: ['tech', 'business'], incomeStyle: ['passive', 'variable'], peopleLevel: 'low', businessType: ['product', 'online_remote'], environment: ['home'], how: 'You identify a problem a specific group of people face, build software that solves it, and charge a monthly subscription. Income is zero for months then compounds fast. 500 customers at $20/month is $10k/month in recurring revenue without you doing more work. Slow and hard to start — but one of the highest-ceiling businesses that exists and one you can eventually sell.' },

  { name: 'No-code / low-code development', cat: 'Software & Tech', cost: 'Free', income: '$2k–$8k/mo', timeToFirst: '3–6 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['nocode', 'tech_general'], physical: false, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['tech', 'business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['online_remote'], environment: ['home'], how: 'Using Bubble, Webflow, or Glide you build real apps and websites for clients without writing code. Small businesses need booking systems, client portals, and internal tools but cannot afford developers. Charge $1,500–$5,000 per project plus $200–$500/month for maintenance. Build reusable templates for one industry and deploy them quickly to multiple clients.' },

  { name: 'AI automation consulting', cat: 'Software & Tech', cost: 'Free', income: '$3k–$10k/mo', timeToFirst: '3–5 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['nocode', 'coding', 'tech_general'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['tech', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['online_remote'], environment: ['home'], how: 'Every business has repetitive tasks they hate doing manually. You use Make and Zapier to automate those workflows and charge $1,000–$3,000 per setup plus a monthly retainer. One satisfied client refers you to five more. Scale into an agency handling automation for entire industries like real estate or e-commerce.' },

  { name: 'Mobile app development', cat: 'Software & Tech', cost: 'Free', income: '$4k–$15k/mo', timeToFirst: '6–10 weeks', diff: 'Advanced', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['tech'], incomeStyle: ['variable', 'passive'], peopleLevel: 'low', businessType: ['product', 'online_remote'], environment: ['home'], how: 'You build iOS and Android apps for clients needing custom tools or build your own app and monetize through the App Store. Client work starts at $5,000 per project. Your own app can generate passive income through subscriptions or purchases. React Native lets you target both platforms from one codebase which cuts your build time in half.' },

  { name: 'WordPress / Webflow development', cat: 'Software & Tech', cost: 'Free', income: '$1.5k–$6k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: false, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['nocode', 'tech_general'], physical: false, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['tech', 'creative', 'business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['online_remote'], environment: ['home'], how: 'You build websites for local businesses — dentists, restaurants, law firms — who have terrible or outdated sites. Charge $1,000–$3,000 per build plus $100–$300/month in maintenance retainers. Ten retainer clients is $1,000–$3,000/month for minimal ongoing work. Scale by hiring junior designers to handle production while you focus on landing new clients.' },

  { name: 'IT support & managed services', cat: 'Software & Tech', cost: 'Free', income: '$2k–$6k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['tech_general'], physical: false, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['tech'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical', 'online_remote'], environment: ['indoors_mobile', 'home'], how: 'Small businesses need someone to keep their computers and networks running and will pay $500–$1,500/month as a flat fee. Most months you barely intervene which means near-pure profit. Scale by adding more business clients and hiring technicians to handle on-site visits while you manage the relationships.' },

  { name: 'Cybersecurity consulting', cat: 'Software & Tech', cost: 'Under $100', income: '$4k–$8k/mo', timeToFirst: '3–6 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding', 'tech_general'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['tech', 'business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote'], environment: ['home'], how: 'Businesses pay well for people who can protect them from breaches. A CompTIA Security+ cert opens the door to freelance security audits at $500–$2,000 each. Start by assessing small businesses for vulnerabilities and grow into a security consulting firm serving multiple businesses on monthly retainer.' },

  { name: 'Local business Google & SEO', cat: 'Software & Tech', cost: 'Free', income: '$1.5k–$5k/mo', timeToFirst: '3–4 weeks', diff: 'Beginner', aiProof: false, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['tech_general', 'nocode'], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['tech', 'business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Most local businesses have unclaimed or broken Google profiles and are invisible to people searching for them. You charge $300–$800 to fix that properly and $200–$400/month to manage and optimize it ongoing. A plumber who now shows up first on Google Maps will pay you indefinitely. Ten clients is $2,000–$4,000/month of recurring income.' },

  { name: 'B2B lead generation', cat: 'Software & Tech', cost: 'Free', income: '$2k–$6k/mo', timeToFirst: '4–6 weeks', diff: 'Intermediate', aiProof: false, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['tech_general', 'sales'], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['business', 'tech'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['online_remote'], environment: ['home'], how: 'Sales teams need a constant flow of qualified prospects but hate doing the research. You use Apollo and LinkedIn to find and verify the right contacts then deliver a list every month for $500–$2,000. You never sell anything yourself — you fill other people\'s pipelines. Scale by serving multiple clients simultaneously with a small research team.' },

  { name: 'Recruiting / talent sourcing', cat: 'Software & Tech', cost: 'Free', income: '$2k–$10k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: false, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['sales', 'tech_general'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['business', 'helping'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['online_remote'], environment: ['home'], how: 'Companies pay 15–25% of a hire\'s first year salary to whoever finds them the right person. A single $80,000 placement earns you $12,000–$20,000. Specialize in one industry, build relationships with both employers and candidates, and scale into a recruiting agency with a team of sourcers each working their own niche.' },

  { name: 'CRM setup & configuration', cat: 'Software & Tech', cost: 'Free', income: '$2k–$8k/mo', timeToFirst: '3–5 weeks', diff: 'Intermediate', aiProof: false, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['tech_general', 'nocode'], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['tech', 'business'], incomeStyle: ['variable', 'steady'], peopleLevel: 'medium', businessType: ['online_remote'], environment: ['home'], how: 'Every growing business needs a CRM to track customers and deals but most owners have no idea how to set one up. You specialize in HubSpot or GoHighLevel, charge $1,500–$5,000 to configure it, and $300–$500/month to maintain and train the team. Scale by building a team of certified specialists handling implementations simultaneously.' },

  { name: 'Micro-SaaS for a specific trade', cat: 'Software & Tech', cost: 'Free', income: '$2k–$15k/mo', timeToFirst: '2–4 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding', 'nocode'], physical: false, goalFit: ['build_business', 'replace_income'], interests: ['tech', 'business'], incomeStyle: ['passive', 'steady'], peopleLevel: 'low', businessType: ['product', 'online_remote'], environment: ['home'], how: 'Pick one trade — pressure washing, lawn care, cleaning — and build the simplest possible scheduling and invoicing tool specifically for them. These business owners are underserved by generic software and will pay $49–$99/month for something that fits how they actually work. 200 customers is $10k/month and the niche makes marketing straightforward.' },

  { name: 'Shopify app development', cat: 'Software & Tech', cost: 'Free', income: '$1k–$20k/mo', timeToFirst: '2–4 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding'], physical: false, goalFit: ['build_business', 'replace_income'], interests: ['tech', 'business'], incomeStyle: ['passive', 'steady'], peopleLevel: 'low', businessType: ['product', 'online_remote'], environment: ['home'], how: 'Millions of Shopify merchants use multiple apps to run their stores. You build one useful app — a loyalty program, a review tool, a shipping calculator — list it on the Shopify App Store, and collect monthly subscription fees from every merchant who installs it. Shopify handles distribution. 500 installs at $19/month is $9,500/month in mostly passive recurring revenue.' },

  { name: 'AI wrapper product', cat: 'Software & Tech', cost: 'Free', income: '$1k–$15k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['coding', 'nocode'], physical: false, goalFit: ['build_business', 'replace_income'], interests: ['tech', 'business'], incomeStyle: ['passive', 'steady'], peopleLevel: 'low', businessType: ['product', 'online_remote'], environment: ['home'], how: 'You take an existing AI model and build a specific product around it for one niche — a contract generator for freelancers, a menu writer for restaurants, a listing description tool for real estate agents. You handle the interface and billing. The AI does the work. Charge $20–$100/month for something that saves people hours every week.' },

  // ── ENTRY LEVEL TRADES ────────────────────────────────────────────
  { name: 'Pressure washing', cat: 'Trades', cost: '$500+', income: '$2k–$8k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'You buy a pressure washer and clean driveways, decks, sidewalks, and building exteriors for homeowners and businesses. Start by knocking on doors in your neighborhood and build from referrals. The scale play is adding equipment and crews to run multiple jobs simultaneously — eventually you manage the business rather than hold the wand.' },

  { name: 'Residential & commercial cleaning', cat: 'Trades', cost: 'Under $100', income: '$2k–$6k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'You clean homes and offices for recurring clients who pay monthly. Start with supplies under $60 and your first client from a neighborhood Facebook group. Commercial cleaning contracts — one office building at $1,500/month — are the real scale play. Build a team of cleaners and move into a management role as the business grows.' },

  { name: 'Lawn care & landscaping', cat: 'Trades', cost: '$100–$500', income: '$2k–$8k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Mow lawns, trim edges, and maintain yards for homeowners on a weekly or bi-weekly schedule. Recurring clients mean predictable income. Add mulching, garden beds, and seasonal cleanups to increase revenue per client. The scale play is multiple crews running routes simultaneously while you manage scheduling and sales.' },

  { name: 'Window cleaning', cat: 'Trades', cost: 'Under $100', income: '$2k–$6k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Clean interior and exterior windows for homes and businesses with squeegees and basic cleaning solution. Commercial clients — storefronts, offices, restaurants — are the real money because they need it done regularly on contract. Low startup cost, low competition from young people, and strong word of mouth in any neighborhood.' },

  { name: 'Holiday lighting installation', cat: 'Trades', cost: '$100–$500', income: '$3k–$20k/season', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['trades', 'events'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Install and remove Christmas lights for homeowners and businesses from October through January. A single install charges $500–$3,000 and clients rebook every year automatically. A two-person crew can do $15k–$20k in December alone. Almost zero competition from young people and the seasonal nature means it stacks perfectly on top of another business like lawn care.' },

  { name: 'Mobile car detailing', cat: 'Trades', cost: '$100–$500', income: '$2k–$7k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['driving'], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades', 'automotive'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'You go to the client\'s home or office and detail their vehicle on-site. No storefront needed. Charge $150–$350 per detail and build a list of recurring monthly clients. Fleet detailing contracts — company vans, rental cars, dealership lots — are the scale play. Add employees, add vehicles, and eventually run a mobile fleet operation.' },

  { name: 'Snow removal & ice management', cat: 'Trades', cost: '$500+', income: '$3k–$12k/season', timeToFirst: '1 week', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['trades', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Plow and shovel driveways, parking lots, and sidewalks after snowstorms. Commercial contracts — businesses, HOAs, churches — pay flat seasonal rates regardless of how many storms hit. That means signed contracts guarantee your income before the first snowflake falls. Pairs perfectly with lawn care to create a year-round outdoor services business.' },

  { name: 'Pool cleaning & maintenance', cat: 'Trades', cost: '$500+', income: '$2k–$6k/mo', timeToFirst: '2–3 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Clean and chemically balance residential and commercial pools on a weekly schedule. Pool owners pay $150–$300/month per pool and barely interact with you. 20 pools is $3,000–$6,000/month for about 20 hours of work. Add equipment repair for significantly higher margins and eventually build a pool service company with multiple technician routes.' },

  { name: 'Handyman & home repair', cat: 'Trades', cost: '$100–$500', income: '$2k–$7k/mo', timeToFirst: '1–2 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Handle the small jobs licensed contractors won\'t take — fixing doors, patching walls, installing fixtures, caulking. Homeowners have a perpetual list of these tasks. Charge $75–$150/hour and build a reputation through Nextdoor and Google reviews. Scale by hiring other skilled generalists and dispatching them to multiple jobs daily.' },

  { name: 'Painting (interior & exterior)', cat: 'Trades', cost: '$100–$500', income: '$2k–$8k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades', 'creative'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'Paint interior rooms and exterior siding for homeowners and landlords. Good prep work and clean edges separate you from cheap painters and justify higher rates. Scale by running crews of two to three painters on simultaneous jobs while you manage estimates and scheduling — eventually becoming a painting contractor rather than a painter.' },

  { name: 'Junk removal & hauling', cat: 'Trades', cost: '$100–$500', income: '$2k–$6k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['driving', 'truck_van'], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Load up unwanted furniture, debris, and clutter and haul it away. Homeowners, landlords, and estate executors all need this regularly. Charge by the truckload at $200–$500 per load. A busy Saturday can earn $1,000–$1,500. Scale by adding trucks and crews and targeting property management companies and real estate investors who need ongoing service.' },

  { name: 'Fence installation & repair', cat: 'Trades', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Install wood, vinyl, and chain-link fences for homeowners and commercial properties. Average job is $2,000–$6,000 with strong material margins. Learn the basics through YouTube and build a portfolio of photos. Scale by running installation crews while you handle estimates and material orders.' },

  { name: 'Gutter cleaning & guard installation', cat: 'Trades', cost: 'Under $100', income: '$1.5k–$5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Clean clogged gutters for homeowners twice a year and install gutter guards as a premium upsell. Fast jobs, simple tools, and very little competition from people your age. One afternoon of gutter cleaning on a single street can earn $500–$800. Scale by targeting property management companies who need entire portfolios serviced on a contract.' },

  { name: 'Drywall & interior finishing', cat: 'Trades', cost: '$100–$500', income: '$2k–$7k/mo', timeToFirst: '2–3 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['trades'], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Patch holes, cracks, and water damage in drywall then sand and texture to match the existing wall. Every homeowner eventually needs this and general contractors need reliable subcontractors for finishing work. Good finishing is a real skill that commands premium rates. Scale by subcontracting to multiple general contractors simultaneously.' },

  { name: 'Tree trimming & removal', cat: 'Trades', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '2–3 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Trim overgrown trees and grind down old stumps for homeowners and municipalities. Equipment rental reduces startup cost initially. Tree work earns strong day rates of $800–$2,500 per job. The scale play is building a full tree service company with certified arborists and larger equipment for commercial and municipal contracts.' },

  { name: 'Soft washing & roof cleaning', cat: 'Trades', cost: '$500+', income: '$2k–$9k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Soft washing uses low-pressure chemical treatment to clean roofs, siding, and fences without damage — more profitable than standard pressure washing. Homeowners pay $300–$800 per roof cleaning and the process takes under two hours. Very little competition and strong repeat business every 2–3 years per property.' },

  { name: 'Cabinet painting & refinishing', cat: 'Trades', cost: '$100–$500', income: '$2k–$7k/mo', timeToFirst: '2–3 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades', 'creative'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Repaint kitchen and bathroom cabinets for homeowners who want a fresh look without replacing them. A kitchen cabinet paint job charges $1,200–$3,500 and takes 2–3 days. Homeowners love the cost savings versus new cabinets and results look nearly identical. Referrals are extremely strong in this niche because every neighbor sees the before and after.' },

  { name: 'Concrete cleaning & sealing', cat: 'Trades', cost: '$500+', income: '$2k–$7k/mo', timeToFirst: '2–3 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['warm_yearround', 'mild', 'four_seasons'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Clean driveways, patios, and concrete surfaces then apply a protective sealer that makes them look new and last longer. Most homeowners have never heard of concrete sealing but will pay $300–$1,000 per driveway once they see what it looks like. Add epoxy garage floor coating as a premium upsell at $2,000–$5,000 per job.' },

  { name: 'Mosquito & pest yard spraying', cat: 'Trades', cost: '$500+', income: '$2k–$7k/mo', timeToFirst: '2–3 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['warm_yearround', 'mild', 'four_seasons'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Spray residential yards for mosquitoes and ticks every 3–4 weeks during warmer months. Homeowners pay $75–$150 per treatment on a recurring subscription. Get your pesticide applicator license — a few days of study in most states — and build a route of 40 properties for strong part-time income that stacks perfectly with lawn care.' },

  { name: 'Trash can cleaning service', cat: 'Trades', cost: '$500+', income: '$2k–$8k/mo', timeToFirst: '2–3 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['warm_yearround', 'mild'], locs: ['mid_city', 'small_town'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['steady', 'passive'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Drive a route on trash day, pressure wash residential bins, and charge $15–$20 per bin per month on subscription. A route of 200 homes is $3,000–$4,000/month and takes one morning a week. Almost zero competition, near-zero churn once subscribed, and completely scalable by adding routes and a second truck. One of the best hidden recurring revenue businesses that exists.' },

  { name: 'TV mounting & smart home installation', cat: 'Trades', cost: 'Under $100', income: '$1.5k–$5k/mo', timeToFirst: '1 week', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['tech_general'], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['trades', 'tech'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Mount TVs, hide cables, and set up smart home devices — Ring doorbells, Nest thermostats, streaming sticks — for homeowners who are not tech-comfortable. Charge $100–$250 per TV mount. Bundle with smart home setup for $300–$500 per visit. Strong upsell to home security camera installation for a recurring monitoring revenue stream.' },

  { name: 'Vacation rental turnover cleaning', cat: 'Trades', cost: 'Under $100', income: '$2k–$6k/mo', timeToFirst: '1 week', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Clean Airbnb and VRBO properties between guest stays on a tight same-day turnaround. Hosts pay $100–$300 per turnover and a busy property needs you weekly. Build a roster of five to ten hosts and you have reliable recurring income. The scale play is managing a team of cleaners and taking on more hosts than you can handle solo — becoming a hospitality cleaning company.' },

  // ── SKILLED TRADES ────────────────────────────────────────────────
  { name: 'Electrician apprenticeship', cat: 'Skilled Trades', cost: 'Free', income: '$2.5k–$5k/mo', timeToFirst: 'Paid from day 1', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'You get paid to learn from day one through a union or non-union apprenticeship. Over 4–5 years you earn your journeyman license commanding $40–$80/hour. The scale play is getting your master electrician license and starting your own electrical contracting company — one of the most stable and lucrative local businesses that exists with strong recurring commercial contracts.' },

  { name: 'Plumbing apprenticeship', cat: 'Skilled Trades', cost: 'Free', income: '$2.5k–$5k/mo', timeToFirst: 'Paid from day 1', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Plumbers are in severe shortage across the US and apprenticeships pay from day one. Emergency plumbing calls at 2am command premium rates. A small plumbing company with two trucks and three plumbers can generate $500k–$1M annually. One of the most recession-proof businesses that exists because leaks don\'t care about the economy.' },

  { name: 'HVAC apprenticeship', cat: 'Skilled Trades', cost: 'Free', income: '$2.5k–$5k/mo', timeToFirst: 'Paid from day 1', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'Install and maintain heating and cooling systems paid from day one through apprenticeship. Demand spikes every summer and winter guaranteeing peak season income. Starting your own HVAC company is one of the most proven local business models — maintenance contracts create predictable recurring revenue year round regardless of economic conditions.' },

  { name: 'Welding (structural & pipe)', cat: 'Skilled Trades', cost: 'Under $100', income: '$3.5k–$8k/mo', timeToFirst: '3–6 months', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'Structural and pipe welders are among the highest-paid tradespeople in the country. Certification takes 3–6 months and opens doors to industrial, construction, and pipeline work. The entrepreneurial path is mobile welding — bringing your rig to farms and construction sites for on-site repairs at $100–$150/hour. Scale into a fabrication shop with a team of certified welders.' },

  { name: 'Water damage restoration', cat: 'Skilled Trades', cost: 'Under $100', income: '$3k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'When pipes burst or basements flood, homeowners call restoration companies who charge $5,000–$30,000 to dry out and repair the damage — mostly paid by insurance. A quick IICRC certification gets you started as a technician and the path to owning a restoration company is clear. Insurance referral relationships with property managers create extremely steady pipelines.' },

  { name: 'Pest control company', cat: 'Skilled Trades', cost: 'Under $100', income: '$2k–$8k/mo', timeToFirst: '4–6 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['trades', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'Get your state pesticide applicator license in a few weeks then treat homes and businesses for roaches, rodents, termites, and ants. Quarterly treatment contracts mean recurring income from the same clients forever. The scale play is building a pest control company with multiple licensed technicians running routes — proven franchise model you can own independently.' },

  { name: 'Solar panel installation', cat: 'Skilled Trades', cost: 'Free', income: '$2.5k–$6k/mo', timeToFirst: '1–2 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Install residential and commercial solar panel systems. Certification takes 1–2 months and demand is growing faster than labor supply. Work for an installer first to build skills then launch your own solar installation company. Government incentives mean homeowners are highly motivated buyers and average install values are $15,000–$40,000 per job.' },

  { name: 'Heavy equipment operation', cat: 'Skilled Trades', cost: '$100–$500', income: '$3.5k–$7k/mo', timeToFirst: '2–4 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Operate excavators, bulldozers, and skid steers on construction and land-clearing sites. Certification courses take 2–4 months. Equipment operators are chronically short-staffed and well paid. The entrepreneurial path is buying or renting equipment and operating as an independent contractor for developers and municipalities — eventually building a full excavation company.' },

  { name: 'Agricultural equipment repair', cat: 'Skilled Trades', cost: '$100–$500', income: '$3k–$7k/mo', timeToFirst: '1–3 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Service and repair tractors, combines, and farm equipment for agricultural operations. Rural areas have a severe shortage of qualified mechanics and farmers pay premium rates to get equipment fixed fast during planting and harvest seasons. A mobile repair rig that comes to the farm commands top dollar. Scale into a full agricultural service company.' },

  // ── HEALTHCARE ────────────────────────────────────────────────────
  { name: 'Sterile processing technician', cat: 'Healthcare', cost: 'Under $100', income: '$2.5k–$4.5k/mo', timeToFirst: '2–3 months', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['medical'], physical: false, goalFit: ['replace_income'], interests: ['health'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Clean and sterilize surgical instruments in hospitals and surgical centers. A short certification is all that is required. Hospitals are always hiring and the job is stable, indoors, and pays well. The entrepreneurial path is launching a private sterile processing services company for outpatient clinics and surgical centers that cannot afford full in-house departments.' },

  { name: 'Phlebotomy technician', cat: 'Healthcare', cost: 'Under $100', income: '$2k–$4k/mo', timeToFirst: '1–2 months', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['medical'], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['health', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Draw blood samples for medical testing in hospitals, clinics, and labs. A short training program is all you need. Mobile phlebotomy — going to patients homes or businesses for blood draws — is a growing niche where you can charge premium rates and build a private practice around corporate wellness programs and concierge healthcare.' },

  { name: 'Home health aide / CNA', cat: 'Healthcare', cost: 'Free', income: '$1.8k–$3.5k/mo', timeToFirst: '4–8 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['medical'], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['health', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Assist elderly or disabled individuals with daily activities in their homes. State CNA certification takes 4–8 weeks. The entrepreneurial path is launching a private duty care agency that employs multiple aides and contracts directly with families — bypassing staffing agencies and keeping the full margin on a deeply meaningful service.' },

  { name: 'Dialysis technician', cat: 'Healthcare', cost: 'Free', income: '$3k–$5k/mo', timeToFirst: '3–6 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city'], skills: ['medical'], physical: false, goalFit: ['replace_income'], interests: ['health'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Operate dialysis machines that filter blood for patients with kidney disease. Training is provided on the job at dialysis centers. Chronic demand — patients need treatment three times a week for life — means this field is completely recession-proof. Strong income, predictable schedule, and meaningful long-term patient relationships.' },

  { name: 'Mobile IV therapy business', cat: 'Healthcare', cost: '$500+', income: '$3k–$12k/mo', timeToFirst: '1–2 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city'], skills: ['medical'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['health', 'wellness'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Bring IV drip hydration and vitamin infusions to clients at their homes, hotels, and offices. Requires a nurse or paramedic license to administer. Charge $150–$300 per session. Corporate wellness programs, hangover relief, and athletic recovery are your main markets. Scale by hiring more nurses and adding a fleet of branded vehicles serving your metro area.' },

  // ── FINANCE & PROFESSIONAL ────────────────────────────────────────
  { name: 'Bookkeeping for small businesses', cat: 'Finance', cost: 'Under $100', income: '$2k–$6k/mo', timeToFirst: '4–6 weeks', diff: 'Intermediate', aiProof: false, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['numbers'], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Manage the financial records of small businesses using QuickBooks or Xero. Owners hate doing their own books and pay $300–$800/month for someone reliable. A QuickBooks certification is enough to start. Ten clients is $3,000–$8,000/month. Scale by hiring other bookkeepers and building a virtual accounting firm that serves clients across the country.' },

  { name: 'Tax preparation', cat: 'Finance', cost: 'Under $100', income: '$3k–$10k/season', timeToFirst: '2–3 months', diff: 'Intermediate', aiProof: false, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['numbers'], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical', 'online_remote'], environment: ['home', 'indoors_mobile'], how: 'File tax returns for individuals and small businesses during tax season. An IRS PTIN and basic tax software is all you need to start. Charge $150–$500 per return. Build a client base that comes back every year automatically. The scale play is opening a year-round tax and financial services firm with multiple preparers on staff.' },

  { name: 'Notary public & loan signing agent', cat: 'Finance', cost: 'Under $100', income: '$1.5k–$5k/mo', timeToFirst: '4–6 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['business'], incomeStyle: ['steady', 'variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Get commissioned as a notary public then add a loan signing agent certification to notarize real estate closing documents. Loan signings pay $75–$200 per appointment and take under an hour. Signing services send you appointments regularly once listed. Extremely flexible schedule with strong per-hour earnings and almost no overhead.' },

  { name: 'Insurance agent', cat: 'Finance', cost: 'Under $100', income: '$2k–$8k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: false, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['sales'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['business', 'helping'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical', 'online_remote'], environment: ['indoors_mobile', 'home'], how: 'Get your state insurance license and sell auto, home, and life insurance products. Commission-based but with massive residual potential — clients renew policies annually and you earn every renewal. Build a large enough book of business and you are earning significant passive income from past work. Own your own agency and hire producers to scale.' },

  { name: 'Real estate wholesaling', cat: 'Finance', cost: 'Free', income: '$2k–$15k/deal', timeToFirst: '2–4 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['sales'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile', 'home'], how: 'Find distressed properties whose owners want to sell quickly, get them under contract at a discount, then sell that contract to an investor for $5,000–$20,000 without ever buying or renovating anything. The entire business is marketing, negotiation, and relationships. Scale by building a team of acquisition specialists and running a full wholesaling operation.' },

  { name: 'Property tax appeals consultant', cat: 'Finance', cost: 'Free', income: '$1k–$6k/mo', timeToFirst: '1–2 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['numbers', 'sales'], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Help homeowners and landlords appeal their property tax assessments when properties are overvalued. You work on contingency — taking 25–50% of whatever tax savings you win them so clients pay nothing upfront. Learn the appeal process in your county, market to property owners, and scale by handling dozens of appeals simultaneously with a small team.' },

  // ── BEAUTY & AESTHETICS ───────────────────────────────────────────
  { name: 'Lash technician', cat: 'Beauty & Aesthetics', cost: '$100–$500', income: '$2k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['beauty', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile', 'home'], how: 'Apply lash extensions for clients who return every 2–3 weeks for fills. A full book of 25–30 lash clients is $4,000–$6,000/month in recurring income. Start in your home or rent a salon suite for $300–$600/month. Scale by renting chairs to other lash artists and taking a percentage of their bookings — turning your suite into a lash studio.' },

  { name: 'Esthetician / skincare specialist', cat: 'Beauty & Aesthetics', cost: '$100–$500', income: '$2.5k–$8k/mo', timeToFirst: '3–6 months', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['beauty', 'health', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Perform facials, chemical peels, and skin treatments for clients with regular skincare routines. State esthetician license takes a few months of school. Once booked out solo the scale play is opening your own aesthetics studio with multiple treatment rooms and practitioners on staff — eventually a full med spa.' },

  { name: 'Permanent makeup & microblading', cat: 'Beauty & Aesthetics', cost: '$500+', income: '$3k–$12k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['beauty', 'creative'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile', 'home'], how: 'Tattoo eyebrows, lips, and eyeliner for clients who want to wake up already looking polished. Microblading appointments charge $400–$800 and clients return annually for touch-ups. High-value low-frequency appointments mean you need far fewer clients than most beauty services. Training costs $1,500–$3,000 but income ceiling justifies it quickly.' },

  { name: 'Hair braiding', cat: 'Beauty & Aesthetics', cost: 'Under $100', income: '$1.5k–$6k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['beauty', 'creative', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['home', 'indoors_mobile'], how: 'Braid hair for clients who return regularly for protective styles. Many states require no license for natural hair braiding. Charge $100–$400 per style. Start from home and build a loyal clientele through word of mouth and Instagram. Scale by renting a dedicated space and hiring other braiders to serve more clients simultaneously.' },

  { name: 'Nail technician', cat: 'Beauty & Aesthetics', cost: '$100–$500', income: '$2k–$6k/mo', timeToFirst: '2–3 months', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['beauty', 'creative'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['home', 'indoors_mobile'], how: 'Do nails for a loyal clientele who book every 2–3 weeks. A nail tech license takes a few months and a home studio setup costs under $500. Charge $60–$120 per appointment and build a book of 30–40 recurring clients for consistent monthly income. Rent a suite or open your own nail studio as you grow.' },

  { name: 'Mobile spray tanning', cat: 'Beauty & Aesthetics', cost: 'Under $100', income: '$1k–$4k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['beauty'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Go to clients homes and apply spray tans before events, vacations, or as a regular beauty ritual. No license required in most states. Equipment costs under $200. Charge $40–$80 per tan. Strong pre-event demand around prom, wedding season, and summer. Build recurring clients and expand with package deals and group bookings for events.' },

  { name: 'Bridal & event makeup artist', cat: 'Beauty & Aesthetics', cost: '$100–$500', income: '$2k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['beauty', 'creative', 'events'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Do makeup for brides, bridesmaids, and event attendees on-location. Bridal parties pay $600–$1,500 for the artist to cover the full wedding party. Build your Instagram portfolio and get listed on wedding vendor directories. Scale by building an agency of makeup artists you dispatch to multiple events simultaneously on peak weekends.' },

  // ── TRANSPORTATION & LOGISTICS ────────────────────────────────────
  { name: 'Box truck delivery business', cat: 'Transportation', cost: '$500+', income: '$3k–$12k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['driving', 'truck_van'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['trades', 'automotive'], incomeStyle: ['steady', 'variable'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Run delivery contracts for Amazon Relay, furniture companies, or local businesses with a rented or owned box truck. One truck solo earns $3,000–$5,000/month. Add a second truck and driver and you double it without working more yourself. The scale play is building a small fleet and landing commercial delivery contracts with retailers or distributors.' },

  { name: 'Non-emergency medical transport (NEMT)', cat: 'Transportation', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['driving', 'truck_van'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['health', 'helping', 'automotive'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Drive patients to dialysis, chemotherapy, and doctor appointments when they cannot drive themselves. Medicaid reimburses most trips so you bill the government rather than the patient. Start with one vehicle, get your state certification, and build contracts with hospitals and nursing homes. Scale from one van to a fleet serving your entire metro area.' },

  { name: 'Freight brokerage', cat: 'Transportation', cost: 'Free', income: '$2k–$15k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: false, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['sales', 'tech_general'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['business', 'automotive'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['online_remote'], environment: ['home'], how: 'Connect shippers who need freight moved with truck drivers who have capacity and pocket the margin. No CDL required — this is a sales and logistics coordination business run from a computer. Get your freight broker license online for under $500 and earn $300–$1,500 per load brokered. Scale by building a team of agents each working their own lanes.' },

  { name: 'Tow truck company', cat: 'Transportation', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: ['driving', 'truck_van'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['automotive', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Tow broken down and illegally parked vehicles for individuals, insurance companies, and municipalities. Get on motor club lists like AAA and Agero for steady dispatch volume. One truck earns $3,000–$5,000/month. Add trucks and drivers and build a towing company with an impound lot for significantly higher revenue and recurring municipal contracts.' },

  // ── AUTOMOTIVE SPECIALTIES ────────────────────────────────────────
  { name: 'Paintless dent repair (PDR)', cat: 'Automotive', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['automotive', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Remove dents from vehicles without painting using specialized metal rods and lighting. A training course takes 4–8 weeks and once mastered commands $75–$150 per dent. Dealerships, rental car companies, and hail damage events are your highest volume clients. Mobile operation means no shop overhead and you go to the car rather than waiting for it to come to you.' },

  { name: 'Auto glass repair & replacement', cat: 'Automotive', cost: '$500+', income: '$3k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['automotive', 'trades'], incomeStyle: ['steady', 'variable'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Repair windshield chips and replace cracked windshields at clients locations or from a small shop. Most jobs are covered by insurance so price resistance is extremely low. A chip repair takes 20 minutes at $60–$100. Full replacements charge $200–$600. Partner with insurance companies for steady referral volume and scale by adding mobile technicians.' },

  { name: 'Mobile mechanic', cat: 'Automotive', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['trades'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['automotive', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Bring your tools to clients homes or workplaces and do oil changes, brake jobs, and repairs on-site. Massive convenience value means clients pay premium rates over traditional shops. No shop lease overhead means higher margins. Start on YourMechanic while building your own client base then scale by hiring certified technicians with their own vans.' },

  { name: 'Car wrap installation', cat: 'Automotive', cost: '$500+', income: '$3k–$10k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['automotive', 'creative', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Apply vinyl wraps to vehicles for color changes, business branding, and paint protection. A full car wrap charges $2,000–$5,000 and takes 1–2 days. Business fleet wraps are particularly lucrative because companies brand multiple vehicles and return for every new one. Scale by opening a shop with multiple installation bays and a design service.' },

  // ── EVENTS & HOSPITALITY ──────────────────────────────────────────
  { name: 'Party rental business', cat: 'Events & Hospitality', cost: '$500+', income: '$3k–$15k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['events', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Buy tables, chairs, tents, and linens and rent them out for birthday parties, weddings, and community events. You deliver, set up, and pick up after. Each item earns revenue multiple times per weekend. A $10,000 equipment investment generating $3,000/weekend in peak season is exceptional ROI. Add bounce houses, concession machines, and dance floors as you grow.' },

  { name: 'Photo booth rental', cat: 'Events & Hospitality', cost: '$500+', income: '$2k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['tech_general'], physical: false, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['events', 'tech', 'creative'], incomeStyle: ['passive', 'variable'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Rent out a photo booth for weddings, corporate events, and parties for $600–$1,500 per booking. Drop it off, it runs itself, you pick it up. One booth doing two bookings per weekend is $5,000–$12,000/month. Add a second booth and you double income without working more. This business operates nearly passively once equipment is on location.' },

  { name: 'Mobile bartending service', cat: 'Events & Hospitality', cost: '$100–$500', income: '$2k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['events', 'food', 'helping'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Provide bartending services at private events — weddings, birthday parties, corporate functions. Get your bartending license and liquor liability insurance then charge $400–$800 per event plus tips. Corporate clients who host regular events are your best recurring customers. Scale by building a team of licensed bartenders dispatched to multiple simultaneous events.' },

  { name: 'Wedding officiant agency', cat: 'Events & Hospitality', cost: 'Free', income: '$1k–$5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['events', 'helping'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['outdoors', 'indoors_mobile'], how: 'Get ordained online for free and legally perform wedding ceremonies charging $300–$800 each. Wedding season runs April through October with peak Saturday demand. Build an agency of officiants covering multiple ceremonies per weekend simultaneously — you take bookings, coordinate officiants, and earn a management fee on every ceremony your network performs.' },

  // ── WELLNESS ──────────────────────────────────────────────────────
  { name: 'Massage therapy practice', cat: 'Wellness', cost: '$100–$500', income: '$2k–$7k/mo', timeToFirst: '3–6 months', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['health', 'wellness', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile', 'home'], how: 'Get your state massage therapy license in 500–600 hours of school and build a private practice. Clients pay $80–$150 per session and the best ones rebook every 2–4 weeks. Work from home, rent a suite, or do mobile massage. Scale by renting treatment rooms to other therapists and taking a percentage — building toward a full wellness studio.' },

  { name: 'Personal training business', cat: 'Wellness', cost: 'Under $100', income: '$2k–$6k/mo', timeToFirst: '4–8 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['health', 'wellness', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Train clients one-on-one or in small groups at gyms, parks, or their homes. A NASM or ACE certification takes a few months. Book 25 sessions per week and you are earning $6,000–$12,000/month. The scale play is opening a private gym, running group programs, or building an online coaching platform that earns while you sleep.' },

  // ── EDUCATION & COACHING ──────────────────────────────────────────
  { name: 'Academic tutoring (STEM)', cat: 'Education', cost: 'Free', income: '$1k–$4k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['teaching'], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['helping', 'business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical', 'online_remote'], environment: ['home', 'indoors_mobile'], how: 'Tutor students in math, science, or standardized tests in person or over Zoom. Charge $40–$100/hour. Parents are highly motivated buyers who pay reliably and refer aggressively. Scale by hiring other tutors and building a tutoring center or agency that places tutors with students for a fee — transitioning from doing the work to running the business.' },

  { name: 'College application coaching', cat: 'Education', cost: 'Free', income: '$2k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['teaching', 'sales'], physical: false, goalFit: ['replace_income', 'build_business'], interests: ['helping', 'business'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Help high school students navigate the college application process — essays, school lists, interviews, financial aid. Families pay $150–$300/hour and junior year students often need 20–40 hours of support. Strong word-of-mouth in communities where college pressure is high. Scale by hiring other coaches and building an admissions consulting firm.' },

  // ── FLIPPING & RESALE ─────────────────────────────────────────────
  { name: 'Furniture flipping', cat: 'Flipping & Resale', cost: 'Under $100', income: '$1k–$5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['value_eye'], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['flipping', 'creative', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['home', 'indoors_mobile'], how: 'Buy old or ugly furniture from thrift stores and Facebook Marketplace for $20–$100, sand and paint it, then resell for $150–$400. Your garage is your workshop and Facebook Marketplace is your store. Scale into a refinishing studio that buys, restores, and sells at volume — or pivot into a bespoke custom furniture brand with a recognizable aesthetic.' },

  { name: 'Thrift store & estate sale resale', cat: 'Flipping & Resale', cost: 'Under $100', income: '$1k–$5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['value_eye'], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['flipping', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Source underpriced items from Goodwill, estate sales, and garage sales then resell on eBay, Facebook, or locally at a profit. The skill is learning what sells and at what price — knowledge that compounds over time. Scale by hiring pickers who source for you while you focus on listing, shipping, and growing the operation into a full resale business.' },

  { name: 'Sneaker & streetwear reselling', cat: 'Flipping & Resale', cost: '$100–$500', income: '$1k–$8k/mo', timeToFirst: '1–2 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['value_eye'], physical: false, goalFit: ['first_dollar', 'side_income', 'replace_income'], interests: ['flipping', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Buy limited-edition sneakers at retail and resell above retail on StockX, GOAT, and eBay. The business is market knowledge — knowing which shoes appreciate and having systems to acquire them at retail. Scale into a consignment shop or online store carrying inventory across multiple brands, or pivot into a full streetwear boutique.' },

  { name: 'Sports cards & collectibles', cat: 'Flipping & Resale', cost: 'Under $100', income: '$500–$6k/mo', timeToFirst: '1–2 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['value_eye'], physical: false, goalFit: ['first_dollar', 'side_income', 'build_business'], interests: ['flipping', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Buy undervalued sports cards and collectibles, submit high-grade cards to PSA for professional grading which dramatically increases their value, and resell at a premium. Market knowledge is your edge. Scale into a card shop or online store and host local buying events that drive traffic and build community around your brand.' },

  { name: 'Vintage clothing resale', cat: 'Flipping & Resale', cost: 'Under $100', income: '$1k–$5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['value_eye'], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['flipping', 'creative', 'beauty'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'local_physical'], environment: ['home'], how: 'Source vintage and thrifted clothing from Goodwill and estate sales then resell on Depop, Poshmark, and Etsy at a premium. Build a curated aesthetic and Instagram following to drive traffic. The scale play is a high-volume online thrift store with multiple pickers and listers working for you — or a physical vintage boutique with a strong local following.' },

  { name: 'Car flipping', cat: 'Flipping & Resale', cost: '$100–$500', income: '$1k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: ['value_eye', 'driving'], physical: true, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['flipping', 'automotive'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Buy undervalued used cars from Facebook Marketplace and auctions, detail and clean them, fix minor issues, and resell for $1,000–$3,000 profit per car. Most states allow 3–5 flips per year without a dealer license. The scale play is getting a dealer license and building a small used car lot — one of the most proven local businesses with a clear path to real revenue.' },

  { name: 'Boat flipping & sales', cat: 'Flipping & Resale', cost: '$500+', income: '$2k–$10k/mo', timeToFirst: '1–3 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: ['value_eye', 'trades'], physical: true, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['flipping', 'automotive', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Buy winterized or cosmetically damaged boats in fall and winter at low prices, restore and clean them, and sell in spring when demand peaks. Boats have high margins and motivated sellers who want them gone before storage fees hit. Specialized knowledge of marine systems dramatically increases your buying edge. Scale into a boat sales and service operation.' },

  { name: 'Motorcycle & powersports flipping', cat: 'Flipping & Resale', cost: '$100–$500', income: '$1k–$5k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['warm_yearround', 'mild', 'four_seasons'], locs: ['mid_city', 'small_town', 'rural'], skills: ['value_eye', 'trades'], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['flipping', 'automotive', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Buy motorcycles, ATVs, and dirt bikes below market from private sellers, service and clean them, and resell at a profit. Lower entry cost than car flipping and a passionate enthusiast market that moves inventory quickly. Specializing in one category — cruisers, sport bikes, or off-road — builds the expertise that makes you a better buyer every time.' },

  { name: 'Appliance repair & resale', cat: 'Flipping & Resale', cost: 'Under $100', income: '$1k–$4k/mo', timeToFirst: '1–2 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: ['trades', 'value_eye'], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['flipping', 'trades'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['home'], how: 'Buy broken washers, dryers, and refrigerators for $20–$50 from people who want them gone, repair them with cheap parts found on eBay, and resell for $200–$400. YouTube has repair guides for almost every model. One repaired appliance per day adds up fast and the skill compounds as you learn the most common failures. Scale into a full appliance repair and resale shop.' },

  { name: 'Liquidation & resale business', cat: 'Flipping & Resale', cost: '$100–$500', income: '$1k–$6k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: ['value_eye'], physical: true, goalFit: ['side_income', 'replace_income'], interests: ['flipping', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical', 'online_remote'], environment: ['home'], how: 'Buy Amazon return pallets and retail overstock at 10–30 cents on the dollar from liquidation websites, sort the contents, and resell individually on eBay, Facebook, or at flea markets. The key skill is knowing what sells before you buy the pallet. Scale into a liquidation warehouse where you sell directly to the public and offer bulk deals to other resellers.' },

  { name: 'Estate sale liquidation company', cat: 'Flipping & Resale', cost: '$100–$500', income: '$2k–$10k/mo', timeToFirst: '1–2 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: ['sales', 'value_eye'], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['flipping', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Contract with families to liquidate the contents of estates — you price, stage, and sell everything from the home keeping 30–40% of total sales. A well-stocked estate can generate $5,000–$20,000 in sales in a single weekend. Build a reputation and an email list of buyers who show up to every sale. Scale by running multiple sales simultaneously with a team.' },

  // ── SERVICE ────────────────────────────────────────────────────────
  { name: 'Dog walking & pet sitting', cat: 'Service', cost: 'Free', income: '$1k–$3k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['nature', 'helping', 'animals'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['outdoors'], how: 'Walk dogs and watch pets for busy owners through Rover and Wag or independently at higher rates. Build a loyal client base in your neighborhood who refer their friends. The scale play is hiring other walkers and sitters and running a pet care agency — taking bookings and dispatching your team rather than doing the walks yourself.' },

  { name: 'Mobile pet grooming', cat: 'Service', cost: '$500+', income: '$3k–$8k/mo', timeToFirst: '2–4 weeks', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['animals', 'nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['outdoors'], how: 'Groom dogs at clients homes from a fully equipped van. Pet owners pay $80–$150 per groom every 4–8 weeks for the convenience of not transporting their dog. Build a full route of recurring clients then add a second groomer and van to scale. Mobile grooming businesses sell for significant amounts once established and routes are full.' },

  { name: 'Airbnb co-hosting & property management', cat: 'Service', cost: 'Free', income: '$1.5k–$6k/mo', timeToFirst: '3–5 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['business'], incomeStyle: ['steady', 'passive', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical', 'online_remote'], environment: ['indoors_mobile', 'home'], how: 'Manage Airbnb properties for owners who do not want to deal with guest communication, cleaning coordination, and pricing. You take 10–30% of revenue without owning anything. Start with one property, prove your systems, and add more. A portfolio of 10–15 properties managed by your team is a legitimate property management company earning $5,000–$15,000/month.' },

  { name: 'Home inspection company', cat: 'Service', cost: 'Free', income: '$2k–$8k/mo', timeToFirst: '1–3 months', diff: 'Intermediate', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income', 'build_business'], interests: ['trades', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile'], how: 'Get your home inspection license and charge $400–$600 per inspection. Real estate transactions require them so demand is consistent with the housing market. Own your own inspection company and hire additional inspectors to multiply income without additional personal time. Real estate agent relationships are your fastest referral source.' },

  { name: 'Grave tending & cemetery maintenance', cat: 'Service', cost: 'Free', income: '$500–$2.5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['nature'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Maintain family graves for people who live far from where their loved ones are buried — cleaning headstones, placing flowers, taking photos to send families. Charge $30–$100 per visit on monthly subscription. Almost no competition, deeply meaningful service, and strong word of mouth through genealogy communities and Facebook groups.' },

  { name: 'Livestock care & farm services', cat: 'Service', cost: 'Free', income: '$1.5k–$3.5k/mo', timeToFirst: '1–2 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['nature', 'trades', 'animals'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical'], environment: ['outdoors'], how: 'Provide farm sitting, animal care, and seasonal labor for rural properties and hobby farms. Farmers need reliable help and pay well for people who show up consistently. Build relationships with multiple farms for steady income and eventually develop the expertise to launch your own agricultural services business or farm management company.' },

  // ── CREATIVE ──────────────────────────────────────────────────────
  { name: 'Real estate photography & video', cat: 'Creative', cost: '$500+', income: '$2k–$7k/mo', timeToFirst: '4–6 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['creative', 'business'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'Shoot listing photos and video walkthroughs for real estate agents who need every property looking its best. Charge $150–$400 per listing. Agents who sell 20+ homes a year need you constantly. Add drone footage and virtual tours for premium upsells. Build a network of agents who call you first and you have a steady predictable business.' },

  { name: 'Drone photography (FAA licensed)', cat: 'Creative', cost: '$500+', income: '$2k–$8k/mo', timeToFirst: '4–6 weeks', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['creative', 'tech', 'nature'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'low', businessType: ['local_physical', 'online_remote'], environment: ['outdoors'], how: 'Get your FAA Part 107 license and shoot aerial photos and video for real estate, construction, events, and agriculture. Clients pay $300–$1,500 per shoot for perspective they cannot get any other way. Construction companies need weekly progress documentation. Real estate agents want drone footage for every listing. Build a roster and scale by adding licensed operators.' },

  { name: 'Wedding & event videography', cat: 'Creative', cost: '$500+', income: '$2k–$8k/mo', timeToFirst: '2–4 months', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['side_income', 'replace_income'], interests: ['creative', 'events'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['indoors_mobile', 'outdoors'], how: 'Film weddings, corporate events, and parties and edit them into polished highlight reels. Couples pay $2,000–$5,000 for wedding video and refer their friends constantly. Editing can be done from anywhere giving you geographic flexibility. Scale by adding a second camera operator on larger events and eventually running a full production company.' },

  { name: 'Music production & licensing', cat: 'Creative', cost: 'Under $100', income: '$500–$5k/mo', timeToFirst: '3–6 months', diff: 'Intermediate', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: false, goalFit: ['side_income', 'build_business'], interests: ['creative'], incomeStyle: ['passive', 'variable', 'no_pref'], peopleLevel: 'low', businessType: ['online_remote', 'product'], environment: ['home'], how: 'Produce beats and music tracks and license them to content creators, filmmakers, and brands who need copyright-free music. Platforms like BeatStars and Musicbed distribute your work globally. Income compounds — every track added to your catalog is another potential earner forever. Scale by producing in volume across multiple genres and building a music licensing label.' },

  // ── FOOD ──────────────────────────────────────────────────────────
  { name: 'Meal prep & personal chef', cat: 'Food', cost: 'Under $100', income: '$1.5k–$5k/mo', timeToFirst: '2–4 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town'], skills: [], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['food', 'helping'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['indoors_mobile', 'home'], how: 'Cook weekly meals for busy professionals and families who want home-cooked food without the time investment. Charge $200–$500 per weekly prep session. Build 8–12 recurring weekly clients and you have predictable income without constant marketing. Scale by hiring sous chefs and taking on more clients than you can personally cook for.' },

  { name: 'Specialty cottage bakery', cat: 'Food', cost: 'Under $100', income: '$1k–$4k/mo', timeToFirst: '4–6 weeks', diff: 'Beginner', aiProof: true, discover: false, climates: ['four_seasons', 'warm_yearround', 'mild'], locs: ['dense_city', 'mid_city', 'small_town', 'rural'], skills: [], physical: false, goalFit: ['first_dollar', 'side_income'], interests: ['food', 'creative'], incomeStyle: ['steady', 'no_pref'], peopleLevel: 'medium', businessType: ['local_physical'], environment: ['home'], how: 'Bake specialty items — custom cakes, sourdough, macarons, dietary-specific treats — from your home kitchen under your state\'s cottage food laws. Sell through Instagram, local markets, and word of mouth. Custom orders for weddings and events are the highest-margin work. Scale into a licensed commercial kitchen and eventually a retail bakery or wholesale operation.' },

  { name: 'Farmers market vendor', cat: 'Food', cost: '$100–$500', income: '$1k–$4k/mo', timeToFirst: '4–8 weeks', diff: 'Beginner', aiProof: true, discover: true, climates: ['warm_yearround', 'mild', 'four_seasons'], locs: ['mid_city', 'small_town', 'rural'], skills: [], physical: true, goalFit: ['first_dollar', 'side_income'], interests: ['food', 'nature', 'helping'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['outdoors'], how: 'Sell homemade food, produce, or artisan goods at weekly farmers markets. Direct community connection, instant feedback, and the ability to test new products without an expensive storefront. Build a loyal customer base that shows up every week and expand to multiple markets. Scale into wholesale accounts with local restaurants and grocery stores.' },

  { name: 'Food truck or pop-up dining', cat: 'Food', cost: '$500+', income: '$3k–$15k/mo', timeToFirst: '1–3 months', diff: 'Advanced', aiProof: true, discover: false, climates: ['warm_yearround', 'mild'], locs: ['dense_city', 'mid_city'], skills: [], physical: true, goalFit: ['replace_income', 'build_business'], interests: ['food', 'events', 'helping'], incomeStyle: ['variable', 'no_pref'], peopleLevel: 'high', businessType: ['local_physical'], environment: ['outdoors'], how: 'Launch a specialty food concept from a truck or pop-up stall at markets, events, and private functions. Lower overhead than a restaurant but still requires significant startup investment and permits. Strong concept and consistent quality build cult followings fast. Scale into multiple trucks, catering contracts, and eventually a brick-and-mortar location.' },
]

const BUDGET_ORDER = ['Free', 'Under $100', '$100–$500', '$500+']

function budgetFits(userBudget: string, pathCost: string): boolean {
  const userIdx = BUDGET_ORDER.indexOf(userBudget)
  const pathIdx = BUDGET_ORDER.indexOf(pathCost)
  if (userIdx === -1 || pathIdx === -1) return true
  return pathIdx <= userIdx
}

function score(opp: typeof OPPS[0], answers: Record<string, string | string[]>): number {
  let pts = 100

  const climate = answers.climate as string
  const location = answers.location_type as string
  const physical = answers.physical as string
  const budget = answers.money as string
  const goal = answers.goal as string
  const userSkills = (answers.skills as string[]) || []
  const userInterests = (answers.interest_area as string[]) || []
  const incomeStyle = answers.income_style as string
  const peoplePref = answers.people_pref as string
  const businessType = answers.business_type as string
  const environment = answers.environment as string
  const time = answers.time as string

  // ── HARD DISQUALIFIER ─────────────────────────────────────────────
  if (physical === 'cant' && opp.physical) return -1

  // ── SOFT PENALTIES ────────────────────────────────────────────────
  if (!opp.climates.includes(climate)) pts -= 35
  if (!opp.locs.includes(location)) pts -= 35
  if (!budgetFits(budget, opp.cost)) {
    const gap = BUDGET_ORDER.indexOf(opp.cost) - BUDGET_ORDER.indexOf(budget)
    pts -= gap * 25
  }
  if (physical === 'prefer_not' && opp.physical) pts -= 20

  // ── INTEREST MATCH — dominant factor ─────────────────────────────
  const matchedInterests = opp.interests.filter(i => userInterests.includes(i))
  pts += matchedInterests.length * 30
  if (userInterests.length > 0 && matchedInterests.length === 0) pts -= 25

  // ── SKILLS MATCH — supporting factor ─────────────────────────────
  const matchedSkills = opp.skills.filter(s => userSkills.includes(s))
  pts += matchedSkills.length * 15
  if (opp.skills.length === 0) pts += 5

  // ── GOAL ALIGNMENT ────────────────────────────────────────────────
  if (opp.goalFit.includes(goal)) pts += 20

  // ── ENVIRONMENT FIT ───────────────────────────────────────────────
  if (opp.environment.includes(environment)) pts += 18
  if (environment === 'no_preference') pts += 8

  // ── INCOME STYLE FIT ──────────────────────────────────────────────
  if (opp.incomeStyle.includes(incomeStyle)) pts += 15
  if (incomeStyle === 'no_pref') pts += 5

  // ── PEOPLE PREFERENCE FIT ─────────────────────────────────────────
  const peopleMap: Record<string, string[]> = {
    love_people: ['high'],
    fine_people: ['medium', 'high'],
    minimal_people: ['low', 'medium'],
    no_people: ['low'],
  }
  if (peoplePref && peopleMap[peoplePref]?.includes(opp.peopleLevel)) pts += 15

  // ── BUSINESS TYPE FIT ─────────────────────────────────────────────
  if (businessType && businessType !== 'unsure' && opp.businessType.includes(businessType)) pts += 15
  if (businessType === 'unsure') pts += 5

  // ── PHYSICAL PREFERENCE BONUS ─────────────────────────────────────
  if ((physical === 'love_it' || physical === 'fine_with_it') && opp.physical) pts += 15
  if ((physical === 'prefer_not' || physical === 'cant') && !opp.physical) pts += 15

  // ── CLIMATE AND LOCATION PERFECT MATCH BONUS ──────────────────────
  if (opp.climates.includes(climate)) pts += 12
  if (opp.locs.includes(location)) pts += 12

  // ── DISCOVERY BONUS ───────────────────────────────────────────────
  if (opp.discover) pts += 6

  // ── TIME FIT ──────────────────────────────────────────────────────
  if (time === 'under5' && opp.diff === 'Beginner') pts += 8
  if (time === '20plus' && ['Advanced', 'Intermediate'].includes(opp.diff)) pts += 8
  if (time === '5to10' && opp.diff === 'Beginner') pts += 6

  return pts
}

function getRankLabel(i: number): string {
  if (i === 0) return 'Best match'
  if (i <= 2) return 'Strong fit'
  if (i <= 4) return 'Great option'
  return 'Worth exploring'
}

function getSummary(answers: Record<string, string | string[]>): string {
  const goal = answers.goal as string
  const location = answers.location_type as string
  const userInterests = (answers.interest_area as string[]) || []

  const goalMap: Record<string, string> = {
    first_dollar: 'making your first dollar',
    side_income: 'building solid side income',
    replace_income: 'replacing a full-time income',
    build_business: 'building something long-term',
  }
  const locMap: Record<string, string> = {
    dense_city: 'a dense city',
    mid_city: 'a mid-size city',
    small_town: 'a small town',
    rural: 'a rural area',
  }

  const interestStr = userInterests.length > 0
    ? ` Your interests in ${userInterests.slice(0, 2).join(' and ')} shaped these results.`
    : ''

  return `Based on your goal of ${goalMap[goal] || 'building a business'} in ${locMap[location] || 'your area'} — here are your 10 best-matched paths ranked by fit.${interestStr} Every path below has a clear line from solo operator to scalable business.`
}

export async function POST(req: NextRequest) {
  const { answers } = await req.json()

  const scored = OPPS
    .map(opp => ({ ...opp, pts: score(opp, answers) }))
    .filter(opp => opp.pts > 0)
    .sort((a, b) => b.pts - a.pts)
    .slice(0, 10)

  const results = scored.map((opp, i) => ({
    title: opp.name,
    category: opp.cat,
    why: opp.how,
    cost: opp.cost,
    timeToFirst: opp.timeToFirst,
    difficulty: opp.diff,
    income: opp.income,
    aiProof: opp.aiProof,
    isDiscovery: opp.discover,
    rankLabel: getRankLabel(i),
  }))

  return NextResponse.json({
    summary: getSummary(answers),
    matches: results,
    total: results.length,
  })
}